### ISSUE TITLE
Image Retrieval Settings

### ISSUE THREAD

**Issue by Yux1angJi** [RingoWRW/UAVD4L#11]
Thanks for your interesting work.

What is the training and test settings in the part _'Rotation-guided Image retrieval'_, do the training and test data just share the same area or are they sampled from different area?

Do you consider about the generalization performance to the unseen area?

Look forward to your reply.

**Comment by RingoWRW** [comment]
I use pre-trained model for retrieval （NetVLAD，OpenIBL..）with a sensor prior. No training for our experiment.

**Comment by Yux1angJi** [comment]
Thanks for your response :)
